server.port=9090
spring.application.name=gusto
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl.auto=update
project.image=images/
spring.datasource.password=12